name: "build"

on:
  push:
    branches:
      - 'bugfix/*'
      - 'feature/*'
      - 'hotfix/*'
      - 'release/*'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: "seemscloud"
    steps:
      - name: "[Repository] Clone"
        uses: actions/checkout@v2
      - name: "[Login] Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          ssh-key: ${{secrets.SSH_BOT_SEEMS_CLOUD}}
      - name: "[Setup] JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: "[Maven] Build (Develop, Versioning Disabled)"
        if: startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/bugfix/') || startsWith(github.ref, 'refs/heads/hotfix/') || startsWith(github.ref, 'refs/heads/release/')
        run: |
          export VERSION_SUFFIX=$(/bin/bash ${GITHUB_WORKSPACE}/.github/scripts/version-suffix.sh)
          mvn clean package --no-transfer-progress
      - name: "[Maven] Build (Release, Versioning Enabled)"
        if: startsWith(github.ref, 'refs/heads/main')
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{secrets.SSH_BOT_SEEMS_CLOUD}}
        run: |
          git config --global user.email "bot@seems.cloud"
          git config --global user.name "Bot"

          export VERSION_SUFFIX=$(/bin/bash ${GITHUB_WORKSPACE}/.github/scripts/version-suffix.sh)
          mvn clean install --no-transfer-progress