name: "release"

on:
  pull_request_target:
    branches: [ 'release/*', 'main' ]
    types: [ closed ]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: "seemscloud"
    steps:
      - name: "[Repository] Clone"
        uses: actions/checkout@v2
      - name: "[Login] Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          ssh-key: ${{secrets.SSH_BOT_SEEMS_CLOUD}}
      - name: "[Setup] JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{secrets.SSH_BOT_SEEMS_CLOUD}}
      - name: "[Maven] Build (Release, Versioning Enabled)"
        run: |
          git config --global user.email "bot@seems.cloud"
          git config --global user.name "Bot"
          
          export VERSION_SUFFIX=$(/bin/bash ${GITHUB_WORKSPACE}/.github/scripts/version-suffix.sh)
          mvn clean install --no-transfer-progress