name: "release"

on:
  push:
    branches:
      - 'release/*'

jobs:
  build-images:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: "seemscloud"
    steps:
      - name: "[Repository] Clone"
        uses: actions/checkout@v2
      - name: "[DockerHub] Login"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "[JDK17] Setup"
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: "[Maven] Install"
        run: |
          git config --global user.email "release@seems.cloud"
          git config --global user.name "ReleaseBot"
          mvn clean install --no-transfer-progress